name: Java CI

on:
  repository_dispatch:
    types: [ build_application ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Run Test
        run: mvn test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: evidences/report.json
  check-results:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Display Test Results
        run: |
          # Get the test results
          echo "Test Results: $(cat test-results.json)"
      - name: Comment Results
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: '*Test Results:*

          ${{ steps.check-results.outputs.test-results }}

          *Warning:* The tests in project B failed'